"""
gen_reports.py - Emit MANUFACTURING_CHECK.md and FINAL_REPORT.md.

Both are generated from the design model plus the router/DRC output, so the
numbers in them are the numbers the files actually contain.

Run:  python scripts/gen_reports.py
"""

from __future__ import annotations

import json
import pathlib
import re
import sys
import xml.etree.ElementTree as ET
from collections import Counter

sys.path.insert(0, str(pathlib.Path(__file__).parent))

import design as D                                          # noqa: E402
import geom                                                 # noqa: E402
from lib_defs import (                                      # noqa: E402
    DEVICESETS,
    LIBRARY_NAME,
    PACKAGE_HEIGHT,
    PACKAGES,
    SYMBOLS,
)

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "documentation"
BRD = ROOT / "pcb" / f"{LIBRARY_NAME}.brd"

HEADER = ("<!-- GENERATED by scripts/gen_reports.py from scripts/design.py "
          "plus the router and DRC output. Do not edit by hand: re-run the "
          "script. -->\n")


def _json(name: str) -> dict:
    f = ROOT / "pcb" / name
    return json.loads(f.read_text(encoding="utf-8")) if f.exists() else {}


def _board():
    txt = BRD.read_text(encoding="utf-8")
    return ET.fromstring(txt.split("\n", 2)[2]).find("./drawing/board")


def _drc_min_clearance(drc: dict) -> str:
    for n in drc.get("notes", []):
        m = re.search(r"MINIMUM COPPER CLEARANCE ANYWHERE ON THE BOARD: "
                      r"([\d.]+) mm", n)
        if m:
            return m.group(1)
    return "see DRC_REPORT.md"


# ===========================================================================
def gen_manufacturing_check() -> str:
    rep, drc = _json("route_report.json"), _json("drc_result.json")
    brd = _board()
    minclear = _drc_min_clearance(drc)

    drills = sorted({float(v.get("drill"))
                     for v in brd.findall("./signals/signal/via")})
    pad_drills = sorted({float(pd.get("drill"))
                         for lib in brd.findall("./libraries/library")
                         for pd in lib.findall(".//package/pad")})
    widths = sorted({float(w.get("width"))
                     for w in brd.findall("./signals/signal/wire")})

    tall = sorted(
        ((PACKAGE_HEIGHT[geom.DS[p.deviceset].package][0],
          PACKAGE_HEIGHT[geom.DS[p.deviceset].package][1], p.ref,
          geom.DS[p.deviceset].package)
         for p in D.PARTS if geom.DS[p.deviceset].package in PACKAGE_HEIGHT),
        reverse=True)

    edges = {"bottom (y < 6 mm)": [], "left (x < 6 mm)": [],
             "right (x > 94 mm)": [], "top (y > 64 mm)": [],
             "interior": []}
    for p in D.PARTS:
        if not p.ref.startswith("J"):
            continue
        if p.by < 6:
            edges["bottom (y < 6 mm)"].append(p.ref)
        elif p.bx < 6:
            edges["left (x < 6 mm)"].append(p.ref)
        elif p.bx > 94:
            edges["right (x > 94 mm)"].append(p.ref)
        elif p.by > 64:
            edges["top (y > 64 mm)"].append(p.ref)
        else:
            edges["interior"].append(p.ref)

    assy = Counter()
    HARD = {"LFCSP-20-4X4-P050", "WSON-6-DRV0006B", "LGA-14L-2.5X3.0"}
    for p in D.PARTS:
        pkg = geom.DS[p.deviceset].package
        if pkg is None:
            continue
        assy["reflow / hot air only" if pkg in HARD
             else ("reflow or hot air (castellated)"
                   if pkg == "ESP32-S3-WROOM-1" else "hand-solderable")] += 1

    L = [HEADER, "# MANUFACTURING CHECK - SIH26113 Maternity Assist Belt\n",
         "Every item the brief asks to check before declaring the design "
         "complete, with the value the files actually contain. Measured "
         "figures come from `validate_drc.py` re-reading the emitted `.brd`; "
         "assumptions are labelled as such.\n",
         "> **No fabricator capability is assumed as verified.** The numbers "
         "below are what the board *requires*. Item 7 is the one that has to "
         "be checked against a specific fab's quoted capability before "
         "ordering - see `REQUIRES_CONFIRMATION.md` H6.\n",
         "| # | Item | Value | Status |", "|---|---|---|---|",
         f"| 1 | PCB dimensions | **{D.BOARD_W:.0f} x {D.BOARD_H:.0f} mm** "
         f"({D.BOARD_W * D.BOARD_H / 100:.0f} cm2) | set in `design.py`, "
         f"outline on layer 20 |",
         f"| 2 | Board thickness | **{D.BOARD_THICKNESS} mm** FR-4 | "
         f"**assumption** - standard; dielectric split "
         f"0.36 / 0.71 / 0.36 mm declared in the rule set |",
         f"| 3 | Layer count | **{D.BOARD_LAYERS}** - "
         f"`(1*2*15*16)`; L2 = GND plane, L15 = 3V3 plane | verified in the "
         f"`.brd` design rules |",
         f"| 4 | Copper thickness | **{D.COPPER_OZ} oz (35 um)** outer and "
         f"inner | **assumption** - drives the trace-width calculation in "
         f"`POWER_BUDGET.md` |",
         f"| 5 | Via sizes | drill **{', '.join(f'{d:g}' for d in drills)} "
         f"mm**, pad 0.55-0.60 mm | {len(brd.findall('./signals/signal/via'))}"
         f" vias, all through (`extent 1-16`) |",
         f"| 6 | Minimum trace width | **{min(widths):g} mm** "
         f"(fine-pitch escapes); {', '.join(f'{w:g}' for w in widths)} mm in "
         f"use | measured from the emitted tracks |",
         f"| 7 | Minimum clearance | **{minclear} mm measured anywhere on the "
         f"board** | 0.15 mm general rule; {D.FINE_PITCH_CLEARANCE} mm inside "
         f"the 4 declared fine-pitch fan-outs. **Needs a fab quoting 5 mil / "
         f"0.127 mm** |",
         f"| 8 | Drill sizes | vias "
         f"{', '.join(f'{d:g}' for d in drills)} mm; plated pads "
         f"{', '.join(f'{d:g}' for d in pad_drills)} mm | JST PH 0.8 mm is "
         f"within JST's ø0.7 +0.1 spec; M2 holes 2.2 mm |",
         f"| 9 | Component courtyard | **no overlaps**, "
         f"{D.COURTYARD_GAP} mm minimum gap between courtyards | DRC rule D2, "
         f"enforced by the placement pass |",
         f"| 10 | Connector accessibility | "
         f"{sum(len(v) for k, v in edges.items() if k != 'interior')} of "
         f"{sum(len(v) for v in edges.values())} connectors are on a board "
         f"edge; see the table below | the "
         f"{len(edges['interior'])} interior ones all take a flying lead from "
         f"an off-board transducer |",
         f"| 11 | Antenna keep-out | **{D.ANTENNA_KEEPOUT[2] - D.ANTENNA_KEEPOUT[0]:.0f}"
         f" x {D.ANTENNA_KEEPOUT[3] - D.ANTENNA_KEEPOUT[1]:.1f} mm** at the "
         f"top edge, flush | no pad, via or track inside it (DRC rule D3); "
         f"both plane polygons are drawn as an L that omits it |",
         f"| 12 | Mounting holes | **{len(D.MOUNT_HOLES)} x M2**, 2.2 mm "
         f"drill, 4.4 mm plated annulus on GND | `H3` is at (2.6, 42) not the "
         f"top-left corner, because that corner is inside the antenna "
         f"keep-out |",
         "| 13 | Assembly feasibility | see the assembly table below | "
         "**3 parts need a stencil and reflow / hot air**; everything else is "
         "hand-solderable |",
         "| 14 | Component availability | **NOT VERIFIED** | distributor stock "
         "could not be checked from this environment. `BOM.csv` carries empty "
         "Supplier / Supplier PN / Lifecycle columns rather than invented "
         "ones |",
         "| 15 | Polarity markings | diodes and LEDs carry a silkscreen "
         "cathode bar; pad 1 = cathode on every 2-pin polarised footprint | "
         "in the library |",
         "| 16 | Pin 1 markings | silkscreen dot or chamfer on every "
         "multi-pin part; **pad 1 is square** on every through-hole connector "
         "| in the library |",
         f"| 17 | Silkscreen readability | reference designators at "
         f"0.8-1.1 mm vector text | **assumption** - most fabs hold 0.8 mm "
         f"with a 0.15 mm stroke; confirm, see `REQUIRES_CONFIRMATION.md` "
         f"L3 |",
         "| 18 | Solder-paste / stencil | **required** | order the stencil "
         "with the boards - see item 13 |",
         "| 19 | Manufacturing outputs | **NOT GENERATED** | Gerbers and "
         "drill files need Fusion's CAM processor; build guide step 19 |",
         "\n## Connector accessibility (item 10)\n",
         "| Edge | Connectors |", "|---|---|"]
    for k, v in edges.items():
        if v:
            L.append(f"| {k} | {', '.join(sorted(v))} |")
    L += ["\nThe interior connectors are the four FSR headers (`J9`-`J12`), "
          "the stretch-sensor header (`J13`) and the optional second AS5600 "
          "(`J6`). All six take a flying lead from a transducer mounted on "
          "the belt, so none of them needs a board edge - and putting the FSR "
          "headers in a vertical row inboard, rather than a long horizontal "
          "row along the edge, was deliberate: a row of through-hole pads "
          "across the board is a wall through both signal layers. See "
          "`DESIGN_ASSUMPTIONS.md` 14.\n",
          "## Assembly feasibility (item 13)\n",
          "| Method | Placements |", "|---|---|"]
    for k, v in sorted(assy.items(), key=lambda kv: -kv[1]):
        L.append(f"| {k} | {v} |")
    L += ["\nThe three parts that cannot be soldered with an iron are the "
          "**AD8232** (0.5 mm-pitch QFN with a 2.50 mm exposed pad), the "
          "**LSM6DSOX** (0.5 mm LGA) and the **TMP117** (0.65 mm WSON with a "
          "thermal pad).\n",
          "## Mechanical envelope\n",
          "No STEP geometry is attached to these footprints, so there is no "
          "solid model and **no 3D interference check has been done**. What "
          "exists instead is a height table (`PACKAGE_HEIGHT` in "
          "`lib_defs.py`) and an isometric extrusion of it in "
          "`renders/pcb_3d.png` - enough to size an enclosure and spot a "
          "connector that will foul a lid, not enough to certify clearance.\n",
          "| Height | Ref | Package | Height source |", "|---|---|---|---|"]
    seen_pkg = set()
    for h, src, ref, pkg in tall:
        if h <= 0 or pkg in seen_pkg:
            continue
        seen_pkg.add(pkg)
        L.append(f"| **{h:.2f} mm** | {ref} | `{pkg}` | {src} |")
    L += [f"\nTallest part: **{tall[0][2]} at {tall[0][0]:.1f} mm** above the "
          f"board, so the minimum internal enclosure height is about "
          f"{D.BOARD_THICKNESS + tall[0][0] + 1.5:.1f} mm including the "
          f"substrate and a little clearance.\n",
          "**Keep the battery and any metal at least 10 mm from the antenna "
          "region** (top edge, x 9-29 mm). A Li-Po pack laid against it will "
          "cost most of the radio range.\n"]
    return "\n".join(L) + "\n"


# ===========================================================================
def gen_final_report() -> str:
    rep, drc = _json("route_report.json"), _json("drc_result.json")
    brd = _board()
    minclear = _drc_min_clearance(drc)
    d6 = [e for e in drc.get("errors", []) if e.startswith("[D6]")]
    other = [e for e in drc.get("errors", []) if not e.startswith("[D6]")]
    conceded = rep.get("conceded_for_clearance", [])
    placed = [p for p in D.PARTS if geom.DS[p.deviceset].package is not None]

    ics = [p for p in D.PARTS if p.ref.startswith("U")]

    L = [HEADER, "# FINAL REPORT - SIH26113 Maternity Assist Belt\n",
         "> **NOT A MEDICAL DEVICE.** Prototype for engineering evaluation. "
         "The ECG channel is not isolated and the board carries no battery "
         "protection circuit. Read `REQUIRES_CONFIRMATION.md` items B1 and B2 "
         "before applying power.\n",
         "## 1. What was created\n",
         "A complete Autodesk EAGLE 9 / Fusion Electronics project for the "
         "SIH26113 Maternity Assist Belt carrier board: a component library "
         "with every pinout verified against the manufacturer's datasheet, a "
         # Counted, not asserted: hard-coded counts in prose have
         # drifted twice in this project already.
         f"seven-sheet schematic, a placed and routed four-layer board, "
         f"{len(list((ROOT / 'renders').glob('*.png')))} "
         f"renders drawn from those files, and "
         f"{len(list((ROOT / 'documentation').glob('*')))} documents.\n",
         "Everything is generated from one source model "
         "(`scripts/design.py`), so the library, schematic, board, netlist, "
         "GPIO table, BOM and reports cannot disagree with each other. The "
         "generators verify themselves: `generate_schematic.py` re-parses its "
         "own output and asserts the netlist matches the model exactly, and "
         "`generate_board.py` does the same for elements and signals.\n",
         "## 2. Exact files generated\n",
         "| Path | What it is |", "|---|---|",
         f"| [`libraries/{LIBRARY_NAME}.lbr`](../libraries/{LIBRARY_NAME}.lbr)"
         f" | EAGLE 9 library: {len(PACKAGES)} footprints, {len(SYMBOLS)} "
         f"symbols, {len(DEVICESETS)} devices |",
         f"| [`schematic/{LIBRARY_NAME}.sch`](../schematic/{LIBRARY_NAME}.sch)"
         f" | 7 sheets, {len(D.PARTS)} parts, {len(D.NETS)} nets |",
         f"| [`pcb/{LIBRARY_NAME}.brd`](../pcb/{LIBRARY_NAME}.brd) | "
         f"4-layer board, {D.BOARD_W:.0f} x {D.BOARD_H:.0f} mm |",
         "| [`pcb/route_report.json`](../pcb/route_report.json) | the "
         "router's own output, machine-readable |",
         "| [`pcb/drc_result.json`](../pcb/drc_result.json) | DRC findings, "
         "machine-readable |"]

    for nm, desc in [
        ("COMPONENT_VERIFICATION.md", "every pinout and footprint with its source"),
        ("DESIGN_ASSUMPTIONS.md", "every decision, and the 7 architecture changes"),
        ("ECG_FRONTEND_DESIGN.md", "the AD8232 circuit, with the arithmetic"),
        ("GROUNDING_NOTES.md", "why one ground plane and not a split"),
        ("POWER_BUDGET.md", "itemised current budget and dropout analysis"),
        ("GPIO_ASSIGNMENT.md", "all 41 module pins [generated]"),
        ("NETLIST.md", "every net, source, load and routing state [generated]"),
        ("BOM.md", "bill of materials [generated]"),
        ("BOM.csv", "bill of materials, machine-readable [generated]"),
        ("ERC_REPORT.md", "rules, result and declared exceptions [generated]"),
        ("DRC_REPORT.md", "rules, result, clearance and airwires [generated]"),
        ("MANUFACTURING_CHECK.md", "the 19-point pre-fabrication check [generated]"),
        ("PROJECT_STATISTICS.md", "counts and metrics [generated]"),
        ("FINAL_REVIEW.md", "27-point independent design review"),
        ("PCB_BUILD_GUIDE.md", "20 steps, Fusion to fabrication"),
        ("REQUIRES_CONFIRMATION.md", "open items, worst first"),
        ("FINAL_REPORT.md", "this document [generated]"),
    ]:
        L.append(f"| [`documentation/{nm}`](./{nm}) | {desc} |")
    for nm, desc in [
        ("schematic_p1.png", "sheet 1 - power entry, charging, 3V3"),
        ("schematic_p2.png", "sheet 2 - ESP32-S3 core"),
        ("schematic_p3.png", "sheet 3 - I2C sensors"),
        ("schematic_p4.png", "sheet 4 - ECG analog front end"),
        ("schematic_p5.png", "sheet 5 - mechanical sensing"),
        ("schematic_p6.png", "sheet 6 - FET-driven alerts"),
        ("schematic_p7.png", "sheet 7 - user input and storage"),
        ("pcb_top.png", "layer 1 copper, pads, silkscreen"),
        ("pcb_bottom.png", "layer 16 copper, mirrored"),
        ("pcb_layers.png", "all four copper layers overlaid"),
        ("pcb_assembly.png", "placement, designators and zones"),
        ("pcb_3d.png", "isometric mechanical envelope"),
    ]:
        L.append(f"| [`renders/{nm}`](../renders/{nm}) | {desc} |")
    L.append("| [`scripts/`](../scripts/) | the 13 generators, routers and "
             "validators that produce all of the above |")

    # ---- 3 / 4. components and variants ---------------------------------
    L += ["\n## 3 & 4. Exact components and variants used\n",
          "Every pinout below was read from the manufacturer's datasheet; the "
          "citation for each is in "
          "[`COMPONENT_VERIFICATION.md`](./COMPONENT_VERIFICATION.md).\n",
          "| Ref | Exact part | Manufacturer | Package | Why this variant |",
          "|---|---|---|---|---|"]
    WHY = {
        "U1": "SOP-8 is hand-solderable and the datasheet gives R_PROG "
              "directly; charge set to 500 mA, not 1 A, because this "
              "footprint has no thermal land",
        "U2": "600 mA guaranteed minimum against a 510 mA worst case, and an "
              "LDO rather than a switcher because the ECG front end is 20 mm "
              "away",
        "U3": "**-N8R2 is mandatory** - octal-PSRAM variants reserve "
              "IO35/36/37, which this design uses",
        "U4": "WSON (DRV) is the only variant in production; TI publish its "
              "land pattern",
        "U5": "LGA-14, I2C mode 1, address 0x6A (SA0 to GND)",
        "U6": "SOIC-8 - by far the easiest fine-position sensor to assemble; "
              "address 0x36 is fixed, which forced the second I2C bus",
        "U7": "**supply 2.0-3.5 V only**, so it is on 3V3 and never on VBAT",
        "U8": "SOP-16, ratiometric to AVDD so sharing the 3V3 rail costs "
              "nothing; RATE grounded for 10 Hz",
    }
    for p in sorted(ics, key=lambda q: int(q.ref[1:])):
        L.append(f"| `{p.ref}` | **{p.mpn or p.value}** | "
                 f"{p.manufacturer or '-'} | "
                 f"`{geom.DS[p.deviceset].package}` | "
                 f"{WHY.get(p.ref, p.desc)} |")
    L += ["| `Q1`, `Q2` | AO3400A (or pin-compatible logic-level N-FET) | "
          "Alpha & Omega | `SOT-23-3` | V_GS(th) low enough for 3.3 V drive |",
          "| `D5`-`D8` | 1N5819HW | generic | `SOD-123` | 40 V / 1 A Schottky "
          "for flyback and piezo clamping |",
          "| `J1`, `J8` | S2B-PH-K-S / S4B-PH-K-S | JST | `JST-PH-2/4` | "
          "PCB hole ø0.7 +0.1 mm read from JST's own board-layout figure |",
          "\nFull line-item list with quantities: "
          "[`BOM.md`](./BOM.md) / [`BOM.csv`](./BOM.csv).\n"]

    # ---- 5. unresolved --------------------------------------------------
    L += ["## 5. Unresolved components\n",
          "| Item | State | Where it is recorded |", "|---|---|---|",
          "| **MAX17048 fuel gauge** | **not placed.** Datasheet unreachable "
          "from this environment, so neither pinout nor land pattern could be "
          "verified. Replaced by header `J4` for a breakout, plus a "
          "470k/470k VBAT divider on `IO9` that works either way | "
          "`REQUIRES_CONFIRMATION.md` H1 |",
          "| **Li-Po protection (DW01A + FS8205A)** | **not placed.** Pinouts "
          "unverifiable; a protected cell/pack is required at `J1` instead | "
          "H1 / **B1 (BLOCKING)** |",
          "| **Stretch sensor** | not selected. `R37` = 10 k is an explicit "
          "**placeholder** - the correct value is the geometric mean of the "
          "chosen sensor's resistance band | H2 |",
          "| **Load cell** | not selected. Bridge resistance and mV/V "
          "sensitivity unknown | H3 |",
          "| **Vibration motor** | not selected. Voltage rating decides "
          "whether `R45` stays at 0 R | **B3 (BLOCKING)** |",
          "| **Buzzer** | active-magnetic assumed; passive piezo works on the "
          "same circuit with PWM | M3 |",
          "| **Piezo film, FSRs, electrodes, hall switch** | not selected; "
          "FSR dividers sized for an FSR402-class part | M4 / "
          "`DESIGN_ASSUMPTIONS.md` 7.1 |",
          "| **Tactile switches** | standard 6.5 x 4.5 mm grid assumed; "
          "confirm the vendor part | H4 |",
          ""]
    L += _sections_6_to_15(rep, drc, brd, minclear, d6, other, conceded,
                           placed)
    return "\n".join(L) + "\n"


def _sections_6_to_15(rep, drc, brd, minclear, d6, other, conceded, placed):
    total = rep.get("total_signal_nets", 0)
    routed = rep.get("routed", 0)
    L = ["## 6. Important design assumptions\n",
         "Full reasoning in "
         "[`DESIGN_ASSUMPTIONS.md`](./DESIGN_ASSUMPTIONS.md). The seven that "
         "**depart from the architecture diagram** are marked.\n",
         "| # | Assumption / decision | Why |", "|---|---|---|",
         "| 1 | **[CHANGE]** No battery protection on the board - a protected "
         "cell/pack is required | DW01A + FS8205A pinouts could not be "
         "verified, and guessing on a lithium protection circuit is not "
         "acceptable |",
         "| 2 | **[CHANGE]** Four layers, not two: signal / GND plane / 3V3 "
         "plane / signal | Measured: on two layers the router finished ~50 of "
         "81 nets and the reachable copper split into disconnected regions. "
         "The AD8232 amplifies a sub-millivolt signal by 1100 and its "
         "datasheet asks for a ground plane |",
         "| 3 | **[CHANGE]** Two I2C busses, not one | AS5600 and MAX17048 "
         "are **both fixed at 0x36**. The diagram's single bus cannot work |",
         "| 4 | **[CHANGE]** MAX17048 replaced by a breakout header plus a "
         "VBAT divider | datasheet unreachable; see section 5 |",
         "| 5 | **[CHANGE]** Two discrete LEDs instead of an RGB | an RGB "
         "needs 3 GPIOs (none spare) and an addressable one needs >= 3.5 V, "
         "which the 3V3 rail cannot supply |",
         "| 6 | **[CHANGE]** microSD as a 6-way module header | no socket "
         "land pattern could be verified, and the diagram itself describes "
         "'module headers' |",
         "| 7 | **[CHANGE]** USB as a 4-way header, not a receptacle | no "
         "USB-C land pattern could be verified; a wrong receptacle makes the "
         "board unprogrammable |",
         "| 8 | AD8232 on **3V3 only** | absolute maximum 3.5 V; VBAT reaches "
         "4.2 V while charging |",
         "| 9 | All 8 analog signals on **ADC1** (GPIO1-10) | ADC2 is "
         "unusable while the radio is active |",
         "| 10 | **-N8R2 module mandatory** | octal-PSRAM variants reserve "
         "IO35/36/37 |",
         "| 11 | One ground net, one continuous plane - **no AGND/DGND "
         "split** | 8 signals cross the analog/digital boundary; one bridge "
         "cannot serve them, and a track crossing a plane split is the very "
         "failure mode a split is meant to avoid |",
         "| 12 | ECG pass band ~7-40 Hz, gain 1100 | the datasheet's "
         "motion-artefact configuration - a belt on a walking subject is not "
         "a resting patient. **A heart-rate channel, not diagnostic ECG** |",
         "| 13 | Charge current 500 mA (`R1` = 2.4 k), not 1 A | halves the "
         "linear charger's dissipation; the SOP-8 footprint has no thermal "
         "land |",
         "| 14 | FSR dividers 10 k | geometric mean of the 2 k-100 k band, so "
         "the output spans 0.30-2.75 V without clipping |",
         "| 15 | Clearance beats completeness | where the router could only "
         "finish a net by breaking the clearance rule it leaves an airwire "
         "instead. An airwire is visible; a 0.05 mm gap is not |",
         ""]
    L += _erc_drc_sections(rep, minclear, d6, other)
    L += _count_sections(rep, placed)
    L += _risk_sections(rep, d6, conceded)
    L += _next_steps(rep, d6, conceded)
    return L


def _erc_drc_sections(rep, minclear, d6, other):
    return [
        "## 7. ERC status\n",
        "**PASS - 0 errors, 0 warnings.** `scripts/validate_erc.py`, 11 rule "
        "groups, run against the same model that generates the `.sch`. "
        f"{len(D.PARTS)} parts, {len(D.NETS)} nets, "
        f"{sum(len(c) for c in D.NETS.values())} pin connections, and every "
        "pin on exactly one net - no floating pins, no pin on two nets.\n",
        "Declared exceptions, each with the datasheet sentence that justifies "
        "it, are in [`ERC_REPORT.md`](./ERC_REPORT.md).\n",
        "> **Autodesk EAGLE / Fusion's own ERC: NOT EXECUTED - TOOL "
        "UNAVAILABLE.** No EAGLE installation existed where these files were "
        "produced. Running it is step 6 of the build guide, where the "
        "exceptions you should expect to approve are pre-listed.\n",
        "## 8. DRC status\n",
        f"**Geometry is clean: {len(other)} clearance, width, drill, "
        f"placement, keep-out or board-edge violations.**\n",
        f"- **measured minimum copper clearance anywhere on the board: "
        f"{minclear} mm** - the figure to quote to the fabricator",
        "- minimum track 0.15 mm (fine-pitch escapes only), minimum drill "
        "0.30 mm",
        f"- the {len(d6)} reported errors are all *unrouted nets*, not "
        f"geometry faults - see section 13",
        "",
        "> **Autodesk EAGLE / Fusion's own DRC: NOT EXECUTED - TOOL "
        "UNAVAILABLE**, and neither is its copper-pour computation. Every "
        "plane-net *pad* has its own dedicated via, so pad connectivity does "
        "not depend on the pour. Build guide steps 14-15.\n",
        "Rules, per-layer minima and every finding: "
        "[`DRC_REPORT.md`](./DRC_REPORT.md).\n",
    ]


def _count_sections(rep, placed):
    total = rep.get("total_signal_nets", 0)
    routed = rep.get("routed", 0)
    npads = sum(len(geom.package_pads(geom.DS[p.deviceset].package))
                for p in placed)
    n = lambda pre: len([p for p in placed if p.ref.startswith(pre)])   # noqa: E731
    L = [
        "## 9. Number of nets\n",
        f"**{len(D.NETS)} nets**, "
        f"{sum(len(c) for c in D.NETS.values())} pin connections.\n",
        f"- {len(D.PLANE_LAYERS)} carried by an inner plane (`GND` on layer "
        f"2, `3V3` on layer 15) - no tracks needed",
        f"- {total} needing tracks, of which **{routed} routed "
        f"({100 * routed // max(total, 1)} %)**",
        "- 2 declared single-pin no-connects (`LDO_NC`, `IMU_OCS_AUX`), each "
        "with a datasheet citation",
        "\nPer-net detail: [`NETLIST.md`](./NETLIST.md).\n",
        "## 10. Number of components\n",
        f"**{len(placed)} placements** ({len(D.PARTS)} schematic parts - the "
        f"difference is {len(D.PARTS) - len(placed)} supply-rail symbols, "
        f"which are not physical parts).\n",
        f"- {n('U')} ICs and modules",
        f"- {n('J')} connectors, {n('SW')} switches, {n('D')} diodes and "
        f"LEDs, {n('Q')} MOSFETs",
        f"- {n('R') + n('C')} passives, {n('TP')} test points, {n('H')} "
        f"mounting holes",
        f"- **{npads} pads** on the board in total",
        "\nLine items and quantities: [`BOM.md`](./BOM.md) / "
        "[`BOM.csv`](./BOM.csv).\n",
        "## 11. PCB dimensions\n",
        f"**{D.BOARD_W:.0f} x {D.BOARD_H:.0f} mm** "
        f"({D.BOARD_W * D.BOARD_H / 100:.0f} cm2), {D.BOARD_THICKNESS} mm "
        f"FR-4.\n",
        "Tallest part is 8.5 mm (a 2.54 mm header with a mated crimp "
        f"housing), so budget about {D.BOARD_THICKNESS + 8.5 + 1.5:.1f} mm of "
        f"internal enclosure height. Mounting holes: {len(D.MOUNT_HOLES)} x "
        f"M2 at "
        f"{', '.join(f'({x:g}, {y:g})' for x, y in D.MOUNT_HOLES)} - note "
        f"`H3` is mid-left-edge rather than a corner, because the top-left "
        f"corner falls inside the antenna keep-out.\n",
        "Envelope render: [`renders/pcb_3d.png`](../renders/pcb_3d.png). "
        "Full pre-fabrication check: "
        "[`MANUFACTURING_CHECK.md`](./MANUFACTURING_CHECK.md).\n",
        "## 12. Layer count\n",
        f"**{D.BOARD_LAYERS} copper layers**, EAGLE layer setup "
        f"`(1*2*15*16)`.\n",
        "| Layer | Role |", "|---|---|",
    ]
    for num, name, role, cu in D.STACKUP:
        L.append(f"| {num} (`{name}`) | {role} |")
    L.append("\nBoth plane polygons are drawn as an **L** that omits the "
             "antenna corner: Espressif require no copper - planes included - "
             "beneath the module antenna, and an EAGLE polygon cannot carry a "
             "hole.\n")
    return L


def _risk_sections(rep, d6, conceded):
    L = ["## 13. Important risks\n",
         "Ordered by consequence.\n",
         "| Risk | Consequence if ignored | Mitigation / where it is recorded |",
         "|---|---|---|",
         "| **No battery protection on the board** | an unprotected Li-Po can "
         "vent or burn on over-charge or short | a cell/pack with an "
         "integrated protection module is **mandatory** at `J1`. "
         "`REQUIRES_CONFIRMATION.md` **B1** |",
         "| **ECG is not isolated** | a subject is galvanically connected "
         "through 330 kOhm; with USB plugged into a mains supply that "
         "reference is the supply's secondary | battery power with USB "
         "disconnected whenever electrodes are attached; bench use with "
         "informed participants only. **B2** |",
         "| **JST battery polarity is not standardised** | reverse-connecting "
         "the cell | `J1` pin 1 = `VBAT`(+), pin 2 = `GND`(-). Check with a "
         "meter before the first connection. **B1** |",
         "| **Motor may be over-volted** | a 3.0 V coin motor on a 4.2 V cell "
         "will not last | `R45` (0 R, 0805) is in series so a ballast can be "
         "fitted without cutting tracks. **B3** |",
         "| **Wrong module variant** | N8R8/N16R8 short the ECG leads-off and "
         "shutdown signals into the PSRAM bus | **-N8R2 only**. **H5** |",
         "| **LDO dropout at low battery** | the 3V3 rail falls below the "
         "ESP32's 3.0 V minimum near the end of discharge, giving "
         "unpredictable brown-outs in a device with an SOS button | firmware "
         "**must** cut off at 3.5 V using `VBAT_SENSE` on `IO9` (1.75 V at "
         "the pin). `POWER_BUDGET.md` |",
         "| **Fab clearance capability** | the fine-pitch fan-outs fail at "
         "the common 6 mil default | requires **5 mil / 0.127 mm**, which is "
         "usually a non-default option. **H6** |",
         "| **Three parts need reflow** | AD8232, LSM6DSOX and TMP117 cannot "
         "be soldered with an iron | order a stencil with the boards. "
         "`BOM.md` |",
         "| **TP4056 has no power-path switching** | load current flows "
         "through the charger and disturbs C/10 termination | accepted for a "
         "prototype; a production build should use MCP73871 or BQ24075. "
         "`DESIGN_ASSUMPTIONS.md` 1.3 |",
         "| **TMP117 measures pod temperature, not skin** | the temperature "
         "channel is close to meaningless as placed | move it to a flex tail "
         "against the skin; the sensor bus is already on `J4`. **M7** |",
         "| **Six of eight transducers are unselected** | `R37` in particular "
         "is a placeholder that will be wrong | project-planning gap rather "
         "than a board gap. **H2, H3, M3, M4** |",
         "| **Pour geometry not computed** | a GND pad could in principle sit "
         "on an orphaned pour island | every plane-net pad has its own "
         "dedicated via, so connectivity does not rely on the pour. Confirm "
         "with `RATSNEST`. Build guide step 14 |",
         ""]
    L += ["## 14. What needs to be verified physically\n",
          "Nothing in this project is a measurement. Every figure is a "
          "datasheet value or a calculation.\n",
          "| Verify | How | Expected |", "|---|---|---|",
          "| 3V3 rail | `TP2` vs `TP3` with 5 V on `J2` | 3.3 V +/-1.5 % |",
          "| Charge current | series meter into `J1` | ~500 mA in constant "
          "current, `D1` lit |",
          "| Battery sense scaling | `IO9` reading vs a meter on `TP1` | pin "
          "= VBAT/2, so 4.2 V -> 2.10 V |",
          "| Brown-out threshold | discharge and watch the 3V3 rail | rail "
          "sags below 3.0 V at roughly 3.3 V of cell |",
          "| I2C bus scan | scan both busses | **0x48 and 0x6A** on the "
          "sensor bus; **0x36** on the angle bus |",
          "| Part orientation | if a device is missing from the scan | the "
          "LSM6DSOX is the usual suspect - pin 1 is top-RIGHT in the "
          "footprint |",
          "| ECG reference | `TP11` (`ECG_REFOUT`) after 2.5 s | ~1.65 V "
          "static |",
          "| ECG output | `TP10` on a scope, electrodes off | idles near "
          "1.65 V; `LOD+`/`LOD-` both high |",
          "| ECG gain and band | inject a known 1 mV, 10 Hz differential "
          "signal | ~1.1 V pk-pk out; -3 dB near 7 Hz and 40 Hz |",
          "| Mains rejection | run on battery near mains wiring | 50/60 Hz "
          "residual should be small; RLD gives ~26 dB |",
          "| Load-cell channel | press the cell | HX711 reading changes "
          "monotonically |",
          "| FSR range | press each FSR | 0.30 V unloaded to ~2.75 V at full "
          "force, no clipping |",
          "| Piezo clamp | tap the film hard | `IO2` stays within 0 - 3.3 V |",
          "| FET fail-safe | power up with motor and buzzer fitted | neither "
          "runs at boot |",
          "| Strapping pins | power up with both LEDs fitted | boots normally "
          "into SPI boot |",
          "| Radio range | with the battery in its final position | keep the "
          "pack >= 10 mm from the antenna |",
          "| Enclosure fit | against `renders/pcb_3d.png` | tallest part "
          "8.5 mm; heights marked *typical* need confirming |",
          ""]
    return L


def _next_steps(rep, d6, conceded):
    L = ["## 15. Exact next steps in Autodesk Fusion\n",
         "The full 20-step walkthrough is in "
         "[`PCB_BUILD_GUIDE.md`](./PCB_BUILD_GUIDE.md). The short version:\n",
         "1. `Library > Open Library Manager > Import` "
         f"`libraries/{LIBRARY_NAME}.lbr`, mark it **In Use**. (The `.sch` and "
         "`.brd` also embed a full copy, so they open without this - it is "
         "only needed to place *new* parts.)",
         "2. Open `schematic/" + LIBRARY_NAME + ".sch`. Confirm 7 sheets and "
         "that every pin carries a green net label on a short stub. "
         "Connections are made by **named labels**, not long wires.",
         "3. Spot-check four footprints against the datasheet pages cited in "
         "`COMPONENT_VERIFICATION.md`: `ESP32-S3-WROOM-1` (pin 1 is 7.49 mm "
         "below the antenna edge), `AD8232`, **`LSM6DSOX` (pin 1 is "
         "top-RIGHT - this is the classic mirror error)**, `TMP117`.",
         "4. `Tools > ERC`. Approve only the exceptions pre-listed in build "
         "guide step 6; investigate anything else.",
         "5. Switch to the `PCB` tab and **type `RATSNEST` immediately** - "
         "that is what makes Fusion compute the copper pours. Nothing looks "
         "right until you do.",
         "6. Confirm the layer setup is `(1*2*15*16)` and that layer 2 holds "
         "one GND polygon and layer 15 one 3V3 polygon, both stopping short "
         "of the antenna corner.",
         f"7. Turn on layer 19 (`Unrouted`) and finish the **{len(d6)} "
         f"airwires** with the interactive router. Set the grid to 0.05 mm, "
         f"enable 45 degree routing, and start from the end of each pad's "
         f"existing fan-out stub rather than from the pad. Use the bottom "
         f"layer freely - it is emptier, and both signal layers sit against a "
         f"plane.",
         "8. `Tools > DRC`. The board carries its own rule set "
         "(`SIH26113_4layer`). Fix anything it reports beyond the airwires.",
         "9. `RATSNEST` again, then check on layer 2 that the GND plane under "
         "the ECG block is unbroken - that is the single most important "
         "electrical property of this board.",
         "10. `PCB > 3D PCB` for a look. Remember **no STEP models are "
         "attached**, so this is not a real interference check; use "
         "`renders/pcb_3d.png` and the height table for the enclosure.",
         "11. `Manufacturing > CAM Processor`, a 4-layer Gerber X2 job. You "
         "need the **top paste** layer too - order a stencil.",
         "12. Tell the fab: 4 layers, 1.6 mm FR-4, 1 oz copper, **5 mil / "
         "0.127 mm trace and gap**, 0.30 mm minimum drill, layers 2 and 15 "
         "are planes.",
         "13. Before ordering, close the BLOCKING items in "
         "`REQUIRES_CONFIRMATION.md` (protected cell, ECG safety protocol, "
         "motor rating) and confirm the module is **-N8R2**.",
         "\nBring-up order once boards arrive is in the build guide: power "
         "only, then the module, then I2C, then mechanical sensing, then "
         "alerts, and **ECG last** - on battery, USB disconnected.\n"]
    if conceded:
        L += ["### The airwires, and why they are airwires\n",
              "These are not routing failures. In each case the router could "
              "*only* finish the net by coming closer than the clearance "
              "rule, so it ripped the net out and left an airwire instead. An "
              "airwire is visible in Fusion the moment the board opens and is "
              "a minute's work to route by hand; a sub-rule gap is invisible "
              "and might reach fabrication.\n",
              "| Net | Closest approach it would have needed | To | Layer |",
              "|---|---|---|---|"]
        for c in conceded:
            L.append(f"| `{c['net']}` | {c['gap_mm']:.3f} mm | "
                     f"`{c['conflicted_with']}` | {c['layer']} |")
        L.append("")
    return L


def main() -> int:
    DOCS.mkdir(parents=True, exist_ok=True)
    for name, text in (("MANUFACTURING_CHECK.md", gen_manufacturing_check()),
                       ("FINAL_REPORT.md", gen_final_report())):
        f = DOCS / name
        f.write_text(text, encoding="utf-8")
        print(f"WROTE {f.relative_to(ROOT)}  ({len(text):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
