"""
generate_docs.py - Emit the generated documentation from the design model.

Everything that is derivable from the design (netlist, GPIO table, BOM,
ERC/DRC reports, statistics) is generated here rather than hand-written, so
these documents cannot drift out of step with the .sch and .brd.

Hand-written documents (README, DESIGN_ASSUMPTIONS, GROUNDING_NOTES,
COMPONENT_VERIFICATION, REQUIRES_CONFIRMATION, PCB_BUILD_GUIDE) live in
documentation/ and are maintained by hand; this script does not touch them.

Run:  python scripts/generate_docs.py
"""

from __future__ import annotations

import csv
import io
import json
import pathlib
import subprocess
import sys
from collections import Counter, defaultdict

sys.path.insert(0, str(pathlib.Path(__file__).parent))

import design as D                              # noqa: E402
import geom                                     # noqa: E402
from lib_defs import DEVICESETS, PACKAGES, SYMBOLS   # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "documentation"
DS = {d.name: d for d in DEVICESETS}
SYM = {s.name: s for s in SYMBOLS}
PKG = {p.name: p for p in PACKAGES}

HEADER = ("<!-- GENERATED by scripts/generate_docs.py from scripts/design.py. "
          "Do not edit by hand: re-run the script. -->\n")


def route_report() -> dict:
    f = ROOT / "pcb" / "route_report.json"
    return json.loads(f.read_text(encoding="utf-8")) if f.exists() else {}


def drc_result() -> dict:
    f = ROOT / "pcb" / "drc_result.json"
    return json.loads(f.read_text(encoding="utf-8")) if f.exists() else {}


def run(script: str) -> str:
    """Run a validator and capture its report text verbatim."""
    r = subprocess.run([sys.executable, str(ROOT / "scripts" / script)],
                       capture_output=True, text=True)
    return r.stdout


# ---------------------------------------------------------------------------
def gen_netlist() -> str:
    rep = route_report()
    unrouted = {nm for nm, _ in rep.get("failed", [])}
    plane = set(D.PLANE_LAYERS.values())

    VOLT = {
        "GND": "0 V", "3V3": "3.3 V", "VBAT": "3.0 - 4.2 V (1S Li-Po)",
        "VBUS": "5 V (USB / charger input)",
    }
    KIND = {}
    for nm in D.NETS:
        if nm in D.POWER_NETS:
            KIND[nm] = "POWER"
        elif nm in D.ECG_NETS:
            KIND[nm] = "ANALOG (ECG)"
        elif nm.endswith("_ADC") or nm in ("VBAT_SENSE", "IO3_SPARE"):
            KIND[nm] = "ANALOG (ADC)"
        elif nm.startswith(("I2C_", "ANG_")):
            KIND[nm] = "DIGITAL I2C (bidirectional / open drain)"
        elif nm.startswith("SD_"):
            KIND[nm] = "DIGITAL SPI"
        elif nm.startswith("USB_"):
            KIND[nm] = "DIGITAL USB 2.0 FS (differential)"
        elif nm in D.MOTOR_NETS or nm.startswith(("MOTOR", "BUZZ")):
            KIND[nm] = "SWITCHED LOAD"
        else:
            KIND[nm] = "DIGITAL"

    out = [HEADER, "# NETLIST - SIH26113 Maternity Assist Belt\n",
           f"{len(D.NETS)} nets, "
           f"{sum(len(c) for c in D.NETS.values())} pin connections, "
           f"{len(D.PARTS)} parts.\n",
           "Source / destination is a design intent, not a topology claim: "
           "most of these nets are multi-drop.  \"Source\" is the pin that "
           "drives the net (a supply, an output, or an open-drain pull-up "
           "node); \"loads\" are the pins that receive it.\n",
           "| Net | Type | Voltage | Source | Loads | Routing | Notes |",
           "|---|---|---|---|---|---|---|"]

    PIN_DIR = {}
    for ds in DEVICESETS:
        for it in SYM[ds.symbol].items:
            if hasattr(it, "direction"):
                PIN_DIR[(ds.name, it.name)] = it.direction

    for nm in sorted(D.NETS):
        conns = D.NETS[nm]
        srcs, loads = [], []
        is_rail = nm in D.POWER_NETS
        for ref, pin in conns:
            p = D.PART_BY_REF[ref]
            d = PIN_DIR.get((p.deviceset, pin), "pas")
            label = f"{ref}.{pin}"
            if is_rail:
                # On a rail, only the supply markers and the regulator or
                # charger outputs drive it.  A logic output strapped to a
                # rail - LSM6DSOX SDO_AUX tied to VDDIO, for instance - is a
                # load of that rail, not its source.
                driving = d == "sup" or (ref in ("U1", "U2") and d == "out")
            else:
                driving = d in ("sup", "out", "oc")
            (srcs if driving else loads).append(label)
        if nm in plane:
            routing = f"inner plane, EAGLE layer {D.PLANE_LAYERS_INV[nm]}"
        elif nm in unrouted:
            routing = "**UNROUTED - airwire**"
        else:
            routing = "routed"
        note = ""
        if nm == "ANG2_OUT":
            note = "only used if R17 (0R, DNP) is fitted"
        if nm == "LDO_NC":
            note = "AP2112 pin 4 is No Connection - intentional"
        load_txt = ", ".join(sorted(loads)) or "-"
        if len(loads) > 14:
            load_txt = (", ".join(sorted(loads)[:14])
                        + f", ... (+{len(loads) - 14} more, {len(conns)} pins total)")
        out.append(
            f"| `{nm}` | {KIND[nm]} | {VOLT.get(nm, '3.3 V logic')} | "
            f"{', '.join(sorted(srcs)) or '-'} | {load_txt} | "
            f"{routing} | {note} |"
        )

    out.append("\n## Net fan-out summary\n")
    out.append("| Net | Pins |")
    out.append("|---|---|")
    for nm, c in sorted(D.NETS.items(), key=lambda kv: -len(kv[1]))[:12]:
        out.append(f"| `{nm}` | {len(c)} |")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
def gen_gpio() -> str:
    out = [HEADER, "# GPIO ALLOCATION - ESP32-S3-WROOM-1-N8R2\n",
           "Pin numbers and alternate functions are from the "
           "*ESP32-S3-WROOM-1 & WROOM-1U Datasheet v1.8*, Table 3-1. "
           "Strapping-pin behaviour is from Section 4 / Table 4-1 of the "
           "same document.\n",
           "**Two hard constraints drove this allocation:**\n",
           "1. **ADC2 is unusable while the radio is on.** Every analog "
           "input therefore lands on ADC1, which is GPIO1-GPIO10 only. "
           "There are 8 analog signals and 10 ADC1 channels, so the budget "
           "is tight by design.\n",
           "2. **IO35/IO36/IO37 are only free on quad-PSRAM parts.** The "
           "datasheet reserves them for the Octal SPI PSRAM in the R8 and "
           "R16V variants. This board uses them, so **-N8R2 is mandatory** "
           "- do not substitute N8R8 or N16R8.\n",
           "| Module pin | Pad | Function | Net | Dir | Boot critical | ADC | "
           "Peripheral | Connected to | Notes |",
           "|---|---|---|---|---|---|---|---|---|---|"]
    for g in D.GPIO_TABLE:
        out.append(
            f"| `{g.pin}` | {g.pad} | {g.func} | `{g.net}` | {g.direction} | "
            f"{'**YES**' if g.boot_critical else 'no'} | {g.adc} | "
            f"{g.peripheral} | {g.component} | {g.notes} |"
        )

    used = [g for g in D.GPIO_TABLE if g.direction != "POWER"]
    adc1 = [g for g in D.GPIO_TABLE
            if g.adc.startswith("ADC1_") and g.direction == "ANALOG IN"]
    adc1_spare = [g for g in D.GPIO_TABLE
                  if g.adc.startswith("ADC1_")
                  and g.direction != "ANALOG IN"]
    out += [
        "\n## Budget\n",
        f"- module pins accounted for: **{len(D.GPIO_TABLE)}** "
        f"(41 physical pads; GND@1, GND@40 and the EPAD share one row)",
        f"- signal pins in use: **{len(used) - 1}** (EN plus every GPIO)",
        f"- ADC1 channels carrying analog: **{len(adc1)} of 10** "
        f"({len(adc1_spare)} more ADC1-capable pins are used digitally "
        f"or held spare: "
        + ", ".join(f"`{g.pin}`" for g in adc1_spare) + ")",
        "- ADC2 channels used for analog: **0** (deliberate - see above)",
        "- strapping pins: `IO0` (boot button), `IO3` (spare, jumper is "
        "unpopulated), `IO45` (status LED), `IO46` (alert LED). The two LEDs "
        "are wired anode-to-GPIO / cathode-to-GND through a resistor, so at "
        "reset the pin is high-impedance, the LED does not conduct, and the "
        "internal weak pull-down holds the strap at its default 0.",
        "- pin-JTAG (IO39-IO42) is given up so those four pins can carry "
        "signals; debugging uses the ESP32-S3's built-in USB-Serial-JTAG on "
        "IO19/IO20 instead.",
        "\n## Free / reserved\n",
        "Nothing is left floating. Every module pad is either driven, "
        "terminated, or brought to a test point - see ERC_REPORT.md.",
    ]
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
def _bom_rows():
    groups = defaultdict(list)
    for p in D.PARTS:
        ds = DS[p.deviceset]
        if ds.package is None:
            continue          # supply symbols are not physical parts
        key = (p.deviceset, p.value, p.mpn, p.manufacturer, ds.package)
        groups[key].append(p.ref)
    rows = []
    for (deviceset, value, mpn, manuf, pkg), refs in groups.items():
        refs = sorted(refs, key=lambda r: (r[0], int("".join(
            ch for ch in r if ch.isdigit()) or 0)))
        desc = DS[deviceset].description.split(".")[0]
        rows.append({
            "Reference": " ".join(refs),
            "Qty": len(refs),
            "Value": value,
            "Manufacturer": manuf or "",
            "MPN": mpn or "",
            "Description": desc,
            "Package": pkg,
            # Deliberately blank: distributor stock and lifecycle status could
            # not be checked from the environment these files were produced
            # in, and a fabricated SKU or an invented "Active" is worse than
            # an empty field.  Fill these in from your own distributor.
            "Supplier": "",
            "Supplier PN": "",
            "Lifecycle": "",
            "Library device": deviceset,
            "Notes": D.PART_BY_REF[refs[0]].desc,
        })
    rows.sort(key=lambda r: (r["Reference"][0], r["Reference"]))
    return rows


def gen_bom_csv() -> str:
    rows = _bom_rows()
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=list(rows[0]), lineterminator="\n")
    w.writeheader()
    w.writerows(rows)
    return buf.getvalue()


def gen_bom_md() -> str:
    rows = _bom_rows()
    total = sum(r["Qty"] for r in rows)
    out = [HEADER, "# BILL OF MATERIALS - SIH26113 Maternity Assist Belt\n",
           f"**{len(rows)} line items, {total} placements.** "
           f"Board: {D.BOARD_W:.0f} x {D.BOARD_H:.0f} mm, "
           f"{D.BOARD_LAYERS}-layer FR-4 {D.BOARD_THICKNESS} mm, "
           f"{D.COPPER_OZ} oz copper.\n",
           "Supplier part numbers are deliberately absent: they were not "
           "verified in this environment, and a fabricated SKU is worse than "
           "no SKU. Manufacturer part numbers below were taken from the "
           "datasheet ordering guides cited in COMPONENT_VERIFICATION.md.\n",
           "Blank MPN = a generic passive or connector where any part meeting "
           "the value and package is acceptable, or a part still to be "
           "selected (see REQUIRES_CONFIRMATION.md).\n",
           "`BOM.csv` carries three further columns - **Supplier**, "
           "**Supplier PN** and **Lifecycle** - deliberately left empty. "
           "Distributor stock and lifecycle status could not be checked from "
           "the environment these files were produced in, and an invented SKU "
           "or an unverified \"Active\" is worse than a blank field. Fill them "
           "in from your own distributor.\n",
           "| Ref | Qty | Value | Manufacturer | MPN | Description | Package |",
           "|---|---|---|---|---|---|---|"]
    for r in rows:
        out.append(f"| {r['Reference']} | {r['Qty']} | {r['Value']} | "
                   f"{r['Manufacturer']} | {r['MPN']} | {r['Description']} | "
                   f"`{r['Package']}` |")

    pkgcount = Counter()
    for p in D.PARTS:
        ds = DS[p.deviceset]
        if ds.package:
            pkgcount[ds.package] += 1
    out += ["\n## Placements by package\n", "| Package | Count | Assembly |",
            "|---|---|---|"]
    ASSY = {
        "R0805": "hand-solderable", "C0805": "hand-solderable",
        "LED0805": "hand-solderable", "SOD-123": "hand-solderable",
        "SOT-23-3": "hand-solderable", "SOT-23-5": "hand-solderable",
        "SOIC-8-N": "hand-solderable", "SOP-16-N": "hand-solderable",
        "ESP32-S3-WROOM-1": "reflow or hot air (castellated, 1.27 mm)",
        "LFCSP-20-4X4-P050": "reflow / hot air only (0.5 mm QFN + exposed pad)",
        "WSON-6-DRV0006B": "reflow / hot air only (0.65 mm + thermal pad)",
        "LGA-14L-2.5X3.0": "reflow / hot air only (0.5 mm LGA)",
        "TESTPOINT-1.5": "n/a (bare land)",
        "MOUNT-M2": "n/a (mechanical)",
    }
    for pkg, c in sorted(pkgcount.items(), key=lambda kv: -kv[1]):
        out.append(f"| `{pkg}` | {c} | "
                   f"{ASSY.get(pkg, 'through-hole, hand-solderable')} |")
    out += [
        "\n## Assembly note\n",
        "Three parts cannot be soldered with an iron: the AD8232 "
        "(0.5 mm-pitch QFN with a 2.5 mm exposed pad), the LSM6DSOX "
        "(0.5 mm LGA) and the TMP117 (0.65 mm WSON with a thermal pad). "
        "They need a stencil and a hotplate/reflow oven, or hot air with "
        "paste. Everything else on the board is 0805, SOT-23, SOIC/SOP-1.27 "
        "or through-hole, all of which are comfortable by hand.\n",
        "## Parts NOT on this board\n",
        "| Function | Why it is off-board |",
        "|---|---|",
        "| MAX17048 fuel gauge | Its data sheet could not be retrieved in "
        "this environment, so its land pattern could not be verified. "
        "Provided as header `J4` for an off-the-shelf breakout, plus an "
        "always-available resistor-divider battery measurement on `IO9`. "
        "See REQUIRES_CONFIRMATION.md. |",
        "| Li-Po protection (DW01A + FS8205A) | A **protected** cell/pack is "
        "required at `J1` instead. Bare protection ICs were not added because "
        "their pinouts could not be verified from primary documentation, and "
        "guessing on a battery-protection circuit is not acceptable. |",
        "| microSD socket | Implemented as a 6-way header (`J18`) for a "
        "standard SPI breakout module, matching the architecture diagram's "
        "'module headers' approach and avoiding an unverified socket "
        "land pattern. |",
        "| Load cell, FSRs, stretch sensor, piezo film, motor, buzzer, "
        "electrodes | Off-board transducers on flying leads. |",
    ]
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
def gen_erc() -> str:
    body = run("validate_erc.py")
    return "\n".join([
        HEADER, "# ERC REPORT - SIH26113 Maternity Assist Belt\n",
        "## How this was produced\n",
        "`scripts/validate_erc.py` runs eleven rule groups against the same "
        "design model that generates the `.sch`, so every finding below is "
        "genuinely present in the schematic. It is **not** Autodesk EAGLE's "
        "own ERC.\n",
        "> **NOT EXECUTED - TOOL UNAVAILABLE:** EAGLE / Fusion Electronics is "
        "not installed in the environment where these files were produced, so "
        "*EAGLE's* ERC has not been run. Running it is step 6 of "
        "PCB_BUILD_GUIDE.md. The independent check below is what can be "
        "claimed today.\n",
        "## Rules checked\n",
        "| # | Rule |",
        "|---|---|",
        "| R1 | reference designators unique; every deviceset exists in the library |",
        "| R2 | every (part, pin) in the netlist names a pin that exists |",
        "| R3 | every pin of every part is on exactly one net - no floating pins, no pin on two nets |",
        "| R4 | no net has fewer than two connections, except declared no-connects |",
        "| R5 | every net feeding a power pin also carries a supply symbol |",
        "| R6 | no net has two or more push-pull outputs |",
        "| R7 | no net has inputs but no driver |",
        "| R8 | each I2C line has exactly one pull-up; no address clash on a bus |",
        "| R9 | ESP32-S3: analog only on ADC1; strapping pins flagged; every module pin in the GPIO table |",
        "| R10 | MOSFET gates have a pull-down; inductive loads have a correctly-oriented flyback diode; clamp polarity |",
        "| R11 | every LED has a series resistor |",
        "\n## Result\n",
        "```", body.rstrip(), "```",
        "\n## Intentional exceptions\n",
        "| Item | Why it is acceptable |",
        "|---|---|",
        "| `LDO_NC` is a single-pin net | AP2112 pin 4 is documented as "
        "\"No Connection\" (Diodes DS39724 Rev.2-2). Leaving it unconnected "
        "is the datasheet's own instruction. Declared explicitly in "
        "`validate_erc.py` rather than silenced. |",
        "| `IMU_OCS_AUX` goes only to test point TP7 | The LSM6DSOX datasheet "
        "(DS12814 Rev.4, Table 1 note 2) says to leave OCS_Aux *electrically* "
        "unconnected but soldered to the board. An isolated land satisfies "
        "both halves of that instruction, and it is not a floating input on a "
        "net with a driver. |",
        "| `TMP_ALERT` goes to a pull-up and a test point, not to a GPIO | "
        "The pin budget has no spare GPIO. TMP117 alerts are readable over "
        "I2C by polling the configuration register, so the hardware ALERT "
        "line is a convenience, not a requirement. |",
        "| `AS_OUT`, `AS_PGO`, `HX_BASE`, `HX_XO` go to test points | All four "
        "are datasheet-designated \"NC when not used\" or optional-function "
        "pins. Bringing them to a land keeps them probeable without "
        "committing a GPIO. |",
        "| `0x36` appears on both I2C busses | This is the resolution of a "
        "real conflict, not an oversight - see DESIGN_ASSUMPTIONS.md. The "
        "AS5600 and the MAX17048 both have a fixed 0x36 address and are "
        "therefore put on physically separate busses. |",
    ]) + "\n"


# ---------------------------------------------------------------------------
def gen_drc() -> str:
    body = run("validate_drc.py")
    rep = route_report()
    failed = rep.get("failed", [])
    total = rep.get("total_signal_nets", 0)
    routed = rep.get("routed", 0)
    pct = (100.0 * routed / total) if total else 0.0

    lines = [
        HEADER, "# DRC REPORT - SIH26113 Maternity Assist Belt\n",
        "## How this was produced\n",
        "`scripts/validate_drc.py` re-parses the emitted `.brd` and measures "
        "the real geometry - segment-to-segment and segment-to-pad distances, "
        "pad bounding boxes, drill sizes, board-edge and keep-out "
        "containment. It deliberately does not share code with the router, "
        "so it can contradict it.\n",
        "> **NOT EXECUTED - TOOL UNAVAILABLE:** Autodesk EAGLE / Fusion "
        "Electronics is not installed here, so *EAGLE's* DRC has not been "
        "run, and neither has its copper-pour computation. The pours in the "
        "`.brd` are declared as polygons; EAGLE calculates their actual shape "
        "when the board is opened and `RATSNEST` is executed. Running EAGLE's "
        "DRC is step 15 of PCB_BUILD_GUIDE.md.\n",
        "## Rules checked\n",
        "| # | Rule |",
        "|---|---|",
        "| D1 | every part's copper is inside the outline with edge clearance |",
        "| D2 | no two component courtyards overlap |",
        "| D3 | nothing (pad, via or track) inside the antenna keep-out |",
        "| D4 | minimum track width and minimum drill |",
        "| D5 | copper clearance, track-to-track and track-to-pad, per layer, "
        "with the declared fine-pitch exception applied by region |",
        "| D6 | routing completeness, from the router's own report |",
        "| D7 | every plane-net pad reaches its plane |",
        "| D9 | board-edge clearance for copper |",
        "\n## Stack-up as emitted\n",
        "| EAGLE layer | Role | Copper |",
        "|---|---|---|",
    ]
    for num, name, role, cu in D.STACKUP:
        lines.append(f"| {num} (`{name}`) | {role} | {cu} |")
    lines += [
        f"\nBoard outline **{D.BOARD_W:.0f} x {D.BOARD_H:.0f} mm**, "
        f"{D.BOARD_THICKNESS} mm FR-4, {D.BOARD_LAYERS} copper layers.\n",
        "\n## Clearance rules, and the one declared exception\n",
        "| Region | Min clearance | Min track |",
        "|---|---|---|",
        f"| General | **{D.GENERAL_CLEARANCE} mm** | 0.20 mm signal, "
        f"0.50 mm power |",
        f"| Inside a fine-pitch fan-out "
        f"({len(D.clearance_exceptions())} regions: AD8232, LSM6DSOX, "
        f"TMP117, HX711) | **{D.FINE_PITCH_CLEARANCE} mm** | 0.15 mm |",
        "\nThe exception is physics, not a fudge: a 0.5 mm-pitch QFN cannot "
        "be escaped at 0.15 mm / 0.15 mm - there is not enough room between "
        "the pads, which is also why the escape tracks are 0.15 mm rather "
        "than 0.20 mm. It applies only inside the named rectangles, "
        "`validate_drc.py` enforces it as such, and any pair between 0.10 "
        "and 0.15 mm inside one of them is listed as a NOTE below rather "
        "than passed silently.\n",
        "> **The board therefore needs a fabricator offering 5 mil / "
        "0.127 mm trace and gap.** That is a standard option (JLCPCB, "
        "PCBWay and most others quote it on 4-layer) but it has to be "
        "selected when ordering - see REQUIRES_CONFIRMATION.md.\n",
        "## Result\n", "```", body.rstrip(), "```",
        "\n## Routing completeness - stated plainly\n",
        f"- signal nets requiring tracks: **{total}**",
        f"- fully routed by the tool: **{routed}** ({pct:.0f}%)",
        f"- left as airwires: **{len(failed)}**",
        f"- plane nets carried by an inner pour (no tracks needed): "
        f"**{len(D.PLANE_LAYERS)}** (`GND` on layer 2, `3V3` on layer 15)",
        f"- tracks emitted: **{rep.get('wires', 0)}** segments",
        f"- vias: **{rep.get('vias', 0)}** total "
        f"({rep.get('plane_vias', 0)} plane-connect, "
        f"{rep.get('thermal_vias', 0)} thermal/exposed-pad, the rest from "
        f"routing)",
        f"- fine-pitch fan-out escapes: **{rep.get('escapes', 0)}**; "
        f"coarse-pitch radial stubs: **{rep.get('radial_stubs', 0)}**",
        f"- **clearance violations, per the independent DRC above: "
        f"see the D5 error count in the Result block - the DRC re-measures "
        f"the emitted geometry and is the authoritative number**",
        f"- the router's own tally was {rep.get('residual_violation_count', 0)}"
        f"; it uses a slightly more conservative test for which fine-pitch "
        f"region a pair falls in, so it can flag a pair the DRC clears",
        f"- measured minimum copper clearance: quoted in the D5 notes in the "
        f"Result block above - that is the figure to give the fabricator",
        f"- rip-up-and-retry attempts: **{rep.get('ripup_attempts', 0)}**; "
        f"orderings tried: **{rep.get('attempts_tried', 1)}**, "
        f"best was seed {rep.get('seed', 0)}",
    ]
    conceded = rep.get("conceded_for_clearance", [])
    if conceded:
        lines += [
            "\n### Nets deliberately left unrouted to protect clearance\n",
            "The router prioritises clearance over completeness. Where every "
            "path it could find came closer than the rule, it **rips the net "
            "out and leaves an airwire** rather than ship a tight gap. An "
            "airwire is visible in Fusion the moment the board opens and is a "
            "minute's work to route by hand; a 0.09 mm gap is invisible and "
            "might reach fabrication.\n",
            "| Net | Came within | Of | Layer |",
            "|---|---|---|---|",
        ]
        for c in conceded:
            lines.append(f"| `{c['net']}` | {c['gap_mm']:.3f} mm | "
                         f"`{c['conflicted_with']}` | {c['layer']} |")
        lines.append("")
    if failed:
        lines += [
            "\n### The airwires that remain\n",
            "These are **not** hidden. Each one appears in Fusion as an "
            "airwire the moment the board is opened, and EAGLE's own DRC will "
            "list them under \"Unrouted\". Finishing them by hand with the "
            "interactive router is step 13 of PCB_BUILD_GUIDE.md and is "
            "unlikely to take more than half an hour: every one of them is a "
            "short connection whose two ends are already fanned out.\n",
            "| Net | Terminal that could not be reached | Reported cause |",
            "|---|---|---|",
        ]
        for nm, why in failed:
            term = why.split(" unreachable")[0]
            cause = why.split("(", 1)[1].split(")")[0] if "(" in why else why
            lines.append(f"| `{nm}` | `{term}` | {cause} |")
        lines += [
            "\n**Why they are hard, and why that is a placement fact rather "
            "than a bug.** All of them terminate on a part whose pads are "
            "fanned out at 1.2-1.9 mm: the ESP32 module (36 signals escaping "
            "a 1.27 mm pitch), the AD8232 (0.5 mm QFN), the LSM6DSOX (0.5 mm "
            "LGA) and the HX711 (whose 9 plane pads each take a via right "
            "beside the pad). Those are the four most congested spots on the "
            "board and they are where a human router also spends their time.\n",
        ]
    else:
        lines.append("\nNo airwires remain: every signal net is fully "
                     "routed.\n")
    lines += [
        "\n## What has *not* been verified here\n",
        "| Item | Status |",
        "|---|---|",
        "| EAGLE/Fusion ERC | NOT EXECUTED - TOOL UNAVAILABLE |",
        "| EAGLE/Fusion DRC | NOT EXECUTED - TOOL UNAVAILABLE |",
        "| Copper-pour CONNECTIVITY | MEASURED by scripts/validate_planes.py - "
        "it punches an antipad (own radius + the declared 0.4 mm isolate) around "
        "every through-hole and via, labels the connected regions, and checks "
        "that every plane-net contact lands in the main one. Live figures: "
        "pcb/plane_result.json. This check found a real defect - two GND vias "
        "outside the pour outline, one of them C7's only path to the ground "
        "plane. See FINAL_REVIEW.md. |",
        "| Copper-pour SHAPE, exactly as EAGLE fills it | NOT COMPUTED - "
        "EAGLE calculates polygons on load. Every plane-net **pad** is given "
        "its own plane via, so pad connectivity does not depend on the pour "
        "shape. Run RATSNEST - build guide step 14. |",
        "| Gerber / drill output | NOT GENERATED - needs EAGLE's CAM processor |",
        "| 3D / mechanical interference | NOT CHECKED - no 3D models are "
        "attached to these footprints |",
        "| Impedance of the USB pair | CALCULATED - see "
        "USB_PAIR_ANALYSIS.md. As-routed ~165 ohm differential, not the "
        "90 ohm USB 2.0 asks for, because the two nets were routed as "
        "ordinary signals (0.806 mm closest gap = 2.24x the dielectric "
        "height, so they are effectively uncoupled). Not a functional "
        "risk: the ESP32-S3 USB is Full Speed only, and 44 mm at "
        "5.8 ps/mm is electrically short by 2.6x against the fastest "
        "4 ns edge USB FS permits. |",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
def gen_stats() -> str:
    rep = route_report()
    pkg = Counter()
    for p in D.PARTS:
        ds = DS[p.deviceset]
        if ds.package:
            pkg[ds.package] += 1
    npins = sum(len(SYM[DS[p.deviceset].symbol].pin_names()) for p in D.PARTS)
    tp = [p for p in D.PARTS if p.deviceset == "TESTPOINT"]
    out = [HEADER, "# PROJECT STATISTICS\n", "| Metric | Value |", "|---|---|",
           f"| Board outline | {D.BOARD_W:.0f} x {D.BOARD_H:.0f} mm "
           f"({D.BOARD_W * D.BOARD_H / 100:.0f} cm2) |",
           f"| Copper layers | {D.BOARD_LAYERS} |",
           f"| Board thickness | {D.BOARD_THICKNESS} mm FR-4 |",
           f"| Outer copper | {D.COPPER_OZ} oz (35 um) |",
           f"| Schematic sheets | {len(D.SHEET_TITLES)} |",
           f"| Parts placed | {len([p for p in D.PARTS if DS[p.deviceset].package])} |",
           f"| Library symbols | {len(SYMBOLS)} |",
           f"| Library footprints | {len(PACKAGES)} |",
           f"| Library devices | {len(DEVICESETS)} |",
           f"| Nets | {len(D.NETS)} |",
           f"| Pin connections | {sum(len(c) for c in D.NETS.values())} |",
           f"| Symbol pins in design | {npins} |",
           f"| Test points | {len(tp)} |",
           f"| Mounting holes | {len(D.MOUNT_HOLES)} (M2) |",
           f"| Track segments | {rep.get('wires', 0)} |",
           f"| Vias | {rep.get('vias', 0)} |",
           f"| Signal nets routed | {rep.get('routed', 0)} / "
           f"{rep.get('total_signal_nets', 0)} |",
           f"| Track widths | 0.15 mm fine-pitch escapes; "
           f"{D.NET_CLASSES[0][2]:g} mm signal; {D.NET_CLASSES[1][2]:g} mm "
           f"power and motor |",
           f"| Minimum drill | 0.30 mm (vias) |",
           f"| Clearance rule | {D.GENERAL_CLEARANCE} mm general; "
           f"{D.FINE_PITCH_CLEARANCE} mm inside the fine-pitch fan-outs |",
           "\n## Placements by footprint\n", "| Footprint | Count |", "|---|---|"]
    for k, v in sorted(pkg.items(), key=lambda kv: -kv[1]):
        out.append(f"| `{k}` | {v} |")
    out += ["\n## Test points\n", "| Ref | Signal | Purpose |", "|---|---|---|"]
    for t in sorted(tp, key=lambda q: int(q.ref[2:])):
        net = next((nm for nm, c in D.NETS.items() if (t.ref, "TP") in c), "-")
        out.append(f"| {t.ref} | `{net}` | {t.desc} |")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
def main() -> int:
    DOCS.mkdir(parents=True, exist_ok=True)
    files = {
        "NETLIST.md": gen_netlist(),
        "GPIO_ASSIGNMENT.md": gen_gpio(),
        "BOM.md": gen_bom_md(),
        "BOM.csv": gen_bom_csv(),
        "ERC_REPORT.md": gen_erc(),
        "DRC_REPORT.md": gen_drc(),
        "PROJECT_STATISTICS.md": gen_stats(),
    }
    for name, text in files.items():
        f = DOCS / name
        f.write_text(text, encoding="utf-8")
        print(f"WROTE {f.relative_to(ROOT)}  ({len(text):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
